language: ruby
script: rspec spec
before_install: gem install bundler -v 1.11.2

services:
  - rabbitmq

rvm:

  - 2.0.0
  - 2.1.1
  - 2.1.2

  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

env:
  global:
    - VERBOSE=true
    - VERBOSE=true

branches:
  only:
    - master

notifications:
  email:
    - adamluzsi@gmail.com
